### PR TITLE
Fix hocr parser

### PR DESCRIPTION
**Pull request by ta4tsering**
- added Hocr_Parser class
- added test

### CODE REVIEW

**Comment by eroux** [comment]
@10zinten @kaldan007 the pull request is ready, can you review it? This is a major code rewrite for the OCR import

**Comment by kaldan007** [comment]
@eroux I run the test and it's working fine. I will be going through the details tomorrow and updating m ocr pipeline.

**Comment by eroux** [comment]
Thanks! I've changed the tests to make them pass, so it's best to check thoroughly

**Comment by kaldan007** [comment]
Sure. will do that tomorrow.

**Comment by kaldan007** [comment]
@eroux https://github.com/OpenPecha/Toolkit/blob/fix-hocr-parser/openpecha/formatters/ocr/ocr.py#L638 the variable buda_data is not defined anywhere. r u referring to self.data_provider.buda_data['source_metadata']['languages']

**Comment by eroux** [comment]
thanks for spotting that @kaldan007 I've addressed it

**Review by 10zinten — APPROVED** [review]

**Pull request merged**
