### PR TITLE
fix(pecha): handle box rotation

### LINKED ISSUE #211: don't produce an remove unneccesary null values in yaml serialization
We now have a lot of `null` values in layers, like in [this example](https://github.com/OpenPecha-Data/I387F38E6/blob/master/I387F38E6.opf/layers/I00KG09835/Pagination.yml). The yaml files are already quite a bottleneck in terms of performance, this certainly will make the problem worse. Before we do more transformations into opf we really need to find a way to fix this issue.

This is linked to https://github.com/OpenPecha/Toolkit/issues/186 (I think) and it's become more apparent in a recent change (I'm not sure which one).

I think a good solution would be to use yaml representers (or something similar) so that a pedantic class can be serialized to yaml  and a yaml file can be read as a pydantic class directly (with no round trip with dictionaries)

### PR DESCRIPTION
**Pull request by eroux**
This:
- fixes #211
- handles vertices coordinates not always in the same order in google_vision json format
- ignores rotated boxes by default
- replaces #212 and #213

### CODE REVIEW

**Comment by eroux** [comment]
@kaldan007 what do you think?

**Comment by kaldan007** [comment]
What I was suggesting was that we hv two kind of order 
43
12 and
41
32. As of now we are using 1 and 2 to get width assuming we will be having the first order only. Since we discovered we hv two kind of order according to their orientation, hence i would suggest to use the diagonal veritices 1 and 3 to compute width n height.

**Comment by eroux** [comment]
ah, right, that makes sense. I made something a bit more sophisticated in this PR, it should be more robust

**Comment by kaldan007** [comment]
I will make the changes n send pr

**Comment by eroux** [comment]
this PR solves that issue in another way, no need to make more changes

**Comment by kaldan007** [comment]
Ok

**Review by 10zinten — APPROVED** [review]

**Pull request merged**
